### ISSUE TITLE
errors running the SbeTool code generator on spot_prod_latest.xml or spot_testnet_latest.xml 

### ISSUE THREAD

**Issue by gborrageiro** [binance/binance-sbe-rust-sample-app#4]
```
% java \
    -Dsbe.output.dir=. \
    -Dsbe.target.language=Rust \
    -jar simple-binary-encoding/sbe-all/build/libs/sbe-all-1.30.0.jar \
    spot_testnet_latest.xml
[Fatal Error] spot_testnet_latest.xml:23:76: Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.
Exception in thread "main" org.xml.sax.SAXParseException; systemId: file:///Users/gabriel/Projects/spot_testnet_latest.xml; lineNumber: 23; columnNumber: 76; Attribute name "crossorigin" associated with an element type "link" must be followed by the ' = ' character.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:132)
	at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:349)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:250)
(base) gabriel@Gabriels-Air Projects % java \
    -Dsbe.output.dir=. \
    -Dsbe.target.language=Rust \
    -jar simple-binary-encoding/sbe-all/build/libs/sbe-all-1.30.0.jar \
    spot_latest.xml 
Exception in thread "main" java.nio.file.NoSuchFileException: spot_latest.xml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:341)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:250)
```

```
% java --version
java 17.0.12 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)
```

```
% uname -a
Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64
```

**Comment by gborrageiro** [comment]
cloned `binance-spot-api-docs` and grab the schema from there
